export const membersData = [
	{
		email: 'lizz@test.com',
		username: 'lizz',
		gender: 'female',
		dateOfBirth: '1999-07-22',
		name: 'Lizz',
		created: '2020-06-24',
		lastActive: '2020-06-21',
		description:
			'Beach lover and early morning runner—nothing beats a sunrise by the ocean. I work in marketing and love anything creative, from photography to styling. Pretty laid-back but always up for a spontaneous road trip. Looking for someone who doesn’t take life too seriously.\r\n',
		city: 'Perth',
		country: 'Australia',
		image: '/images/lizz.jpg',
	},
	{
		email: 'amanda@test.com',
		username: 'amanda',
		gender: 'female',
		dateOfBirth: '1992-10-12',
		name: 'Amanda',
		created: '2019-12-09',
		lastActive: '2020-05-06',
		description:
			'Big fan of good tea, long walks, and meaningful conversations. I work in finance, but outside of that, I’m usually at a gallery or trying a new restaurant. I appreciate honesty and a bit of dry humor. Bonus points if you can recommend a great book.\r\n',
		city: 'London',
		country: 'England',
		image: '/images/amanda.jpg',
	},
	{
		email: 'hannah@test.com',
		username: 'hannah',
		gender: 'female',
		dateOfBirth: '2003-08-05',
		name: 'Hannah',
		created: '2019-08-10',
		lastActive: '2020-05-12',
		description:
			'Just graduated from  Stanford University. I was majoring psychology, always curious about how people think. I spend most of my free time at the beach or with friends, probably laughing too loud. Easygoing and a little bit goofy. Just looking to meet genuine people and see where it goes.\r\n',
		city: 'San Diego',
		country: 'USA',
		image: '/images/hannah.jpg',
	},
	{
		email: 'misato@test.com',
		username: 'misato',
		gender: 'female',
		dateOfBirth: '1994-06-22',
		name: 'Misato',
		created: '2019-04-24',
		lastActive: '2020-06-17',
		description:
			'I enjoy slow mornings, good matcha, and exploring hidden spots around the city. I work in design and love creating things that feel simple but thoughtful. Calm personality, but I enjoy deep conversations. Looking for someone kind and grounded.\r\n',
		city: 'Kyoto',
		country: 'Japan',
		image: '/images/misato.jpg',
	},
	{
		email: 'maria@test.com',
		username: 'maria',
		gender: 'female',
		dateOfBirth: '1989-01-12',
		name: 'Maria',
		created: '2019-04-30',
		lastActive: '2020-06-21',
		description:
			'Architect by profession, passionate about design, culture, and travel. I love discovering new places, especially local food spots. Family and close friendships mean a lot to me. Looking for someone who’s genuine, open-minded, and enjoys life’s little moments.',
		city: 'Ciudad de México',
		country: 'Mexico',
		image: '/images/maria.jpg',
	},
	{
		email: 'josh@test.com',
		username: 'josh',
		gender: 'male',
		dateOfBirth: '1997-02-07',
		name: 'Josh',
		created: '2019-04-29',
		lastActive: '2020-05-16',
		description:
			'Born and raised in Hawaii, I’m all about ocean life and staying active. I work remotely in tech, so I try to balance it out with surfing or hiking. Pretty easygoing, but I value people who are genuine and grounded. Looking for something real, not rushed.\r\n',
		city: 'Hawaii',
		country: 'USA',
		image: '/images/josh.jpg',
	},
	{
		email: 'albert@test.com',
		username: 'albert',
		gender: 'male',
		dateOfBirth: '1984-04-09',
		name: 'Albert',
		created: '2020-04-05',
		lastActive: '2020-06-23',
		description:
			'I’ve built my career in consulting, but these days I’m more focused on enjoying the city at my own pace. Big fan of jazz, good wine, and conversations that go a little deeper. I appreciate independence and emotional maturity. Not into games—just real connection.\r\n',
		city: 'New York',
		country: 'USA',
		image: '/images/albert.jpg',
	},
	{
		email: 'chris@test.com',
		username: 'chris',
		gender: 'male',
		dateOfBirth: '1989-03-23',
		name: 'Chris',
		created: '2020-03-14',
		lastActive: '2020-05-17',
		description:
			'Work in logistics, but outside of that, I’m usually at the gym or catching a game. I’m straightforward, loyal, and have a pretty dry sense of humor. Not the flashiest guy, but I show up when it counts. Looking for someone who values consistency.\r\n',
		city: 'Chicago',
		country: 'USA',
		image: '/images/chris.jpg',
	},
	{
		email: 'eric@test.com',
		username: 'eric',
		gender: 'male',
		dateOfBirth: '1992-12-01',
		name: 'Eric',
		created: '2019-01-28',
		lastActive: '2020-06-07',
		description:
			'I work in product design and enjoy building things that people actually use. Big on good tea, cycling around the city, and the occasional weekend getaway. I’m calm, thoughtful, and a bit sarcastic once you get to know me. Looking for something meaningful.\r\n',
		city: 'London',
		country: 'England',
		image: '/images/eric.jpg',
	},
	{
		email: 'gabriel@test.com',
		username: 'gabriel',
		gender: 'male',
		dateOfBirth: '1999-08-10',
		name: 'Gabriel',
		created: '2020-02-25',
		lastActive: '2020-06-11',
		description:
			'Love being outdoors—beach, hikes, anything with sun. I work in fitness, so staying active is a big part of my life. Pretty social and always up for meeting new people. Looking for someone who’s positive, fun, and enjoys a bit of adventure.\r\n',
		city: 'Sydney',
		country: 'Australia',
		image: '/images/gabriel.jpg',
	},
	{
		email: 'kaito@test.com',
		username: 'kaito',
		gender: 'male',
		dateOfBirth: '1998-12-24',
		name: 'Kaito',
		created: '2020-02-25',
		lastActive: '2020-06-11',
		description:
			'Working in IT, mostly backend, and I enjoy solving problems quietly. I’m not the loud type, but I care about the people close to me. On weekends, I like running or just walking around the city. Looking for someone I can feel comfortable being myself with.\r\n',
		city: 'Tokyo',
		country: 'Japan',
		image: '/images/kaito.jpg',
	},
	{
		email: 'ian@test.com',
		username: 'ian',
		gender: 'male',
		dateOfBirth: '2002-02-20',
		name: 'Ian',
		created: '2020-02-25',
		lastActive: '2020-06-11',
		description:
			'Studying engineering and figuring things out one step at a time. I like learning new things, whether it’s tech, languages, or just random topics. Friends say I’m easy to talk to and a bit of a thinker. Open to meeting someone genuine and seeing where it goes.\r\n',
		city: 'Istanbul',
		country: 'Turkey',
		image: '/images/ian.jpg',
	},
];
