import type { Metadata } from 'next';
import './globals.css';
import { Inter, Cormorant } from 'next/font/google';

import AppProviders from '@/providers/AppProviders';
import { Toaster } from 'sonner';
import BottomNavWrapper from '@/components/navigation/mobile/BottomNavWrapper';

export const metadata: Metadata = {
	title: 'The One',
	description: 'Generated by create next app',
};

const inter = Inter({
	subsets: ['latin'],
	variable: '--font-sans',
});

const cormorant = Cormorant({
	subsets: ['latin'],
	weight: ['400', '600', '700'],
	variable: '--font-display',
});

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en' className={`${inter.variable} ${cormorant.variable}`}>
			<body className='font-sans'>
				<AppProviders>
					{children}
					<Toaster position='bottom-right' />
					{/* ↓ここもGuest, Authに分ける */}
					<BottomNavWrapper />
				</AppProviders>
			</body>
		</html>
	);
}
