import type { Metadata } from 'next';
import './globals.css';
import Providers from '@/components/Providers';
import { Inter, Cormorant } from 'next/font/google';
import TopNav from '@/components/navigation/TopNav';
import { Toaster } from 'sonner';
import BottomNavWrapper from '@/components/navigation/BottomNavWrapper';

export const metadata: Metadata = {
	title: 'The One',
	description: 'Generated by create next app',
};

const inter = Inter({
	subsets: ['latin'],
	variable: '--font-sans',
});

const cormorant = Cormorant({
	subsets: ['latin'],
	weight: ['400', '600', '700'],
	variable: '--font-display',
});

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en' className={`${inter.variable} ${cormorant.variable}`}>
			<body className='font-sans'>
				<Providers>
					<TopNav />
					<main className='min-h-[calc(100vh-80px)] mx-auto px-6 p-10 pb-36 lg:pb-24'>
						<div className='max-w-6xl mx-auto'>{children}</div>
					</main>
					<Toaster position='bottom-right' />
					<BottomNavWrapper />
				</Providers>
			</body>
		</html>
	);
}
